# Basic Python

## 1. Split this string

In [2]:
s = "Hi there Sam!"

In [1]:
s = "Hi there Sam!"
a=s.split()
print(a)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [4]:
planet="Earth"
diameter=12742
print(f"The diameter of {planet} is {diameter} kilometers.")

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [5]:
d = { 'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
printf=(d['k1'][3]['tricky'][3]['target'][3])

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
import numpy as np
array1=np.array([0,0,0,0,0,0,0,0,0,0])
print(array1)

In [ ]:
import numpy as np
array2=np.array([5,5,5,5,5,5,5,5,5,5])
print(array2)

## 5. Create an array of all the even integers from 20 to 35

In [ ]:
import numpy as np1
array3=np1.arange(20,35,2)
print(array3)

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [6]:
import numpy as np
x = np.arange(0,8+1).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a,b),axis=0)

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [8]:
import pandas as pd
data = {'column1': ['1','2','3'],
        'column2': ['4','5','6']}
dataframe = pd.DataFrame(data, index=['row1',
                                'row2',
                                'row3'])
dataframe

column1 column2
row1       1       4
row2       2       5
row3       3       6

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [12]:
import pandas as pd
d1 = pd.date_rane(start = '1-1-2023',
   end = '02-10-2023')
 for val in d1:
   print(val)

IndentationError: ignored

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [11]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [10]:
import pandas as pd
lists =[[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
dataframe = pd.DataFrame(lists, columns =['column1', 'column2', 'column3'])
printf=(dataframe)